ESAMNew/natteravnen-esam-5b5fb689aa6c/IdeaCms/Controllers/DenskIdController.cs
using System.Configuration;
using System.Web.Hosting;
using System.Web.Mvc;
using SPS.Client.Frame;
using SPS.Client.Frame.NemId;
using IdeaCms.Filters;

namespace IdeaCms.Controllers
{
    [Localization]
    public class DenskIdController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult Logon()
        {
            ViewBag.Maintitle = "NemID Logon";
            UpdateViewBagWithNemIdParameters(new NemIDFrameBuilder());
            return View();
        }

        public ActionResult SignPdf()
        {
            ViewBag.Maintitle = "NemID Signature (PDF)";
            var path = ConfigurationManager.AppSettings["testPdfPath"];
            if (!System.IO.File.Exists(path))
            {
                path = HostingEnvironment.MapPath(ConfigurationManager.AppSettings["testPdfPath"]);
            }
            var frameBuilder = new NemIDSignFrameBuilder()
                .SignPdf(System.IO.File.ReadAllBytes(path));

            UpdateViewBagWithNemIdParameters(frameBuilder);

            return View();
        }

        public ActionResult SignText()
        {
            ViewBag.Maintitle = "NemID Signature (Text)";
            const string messageToBeSigned = "IT-løsning fra Signaturgruppen\nLicens og assistance\n\n\nDer tilbydes kontrakt mellem parterne...";
            UpdateViewBagWithNemIdParameters(new NemIDSignFrameBuilder().SignText(messageToBeSigned));

            return View();
        }

        private void UpdateViewBagWithNemIdParameters(FrameBuilder frameBuilder)
        {
           // parent.postMessage('obj.AuthenticationInfo.Pid', 'http://localhost:50448/');
            var v = Url.Action("HandleBackendResponse", "Home");
            string test = frameBuilder.GetScript(v);

            var targetSite = ConfigurationManager.AppSettings["targetSite"];
            // window.alert(obj.message); 
            string replace = test.Replace("document.body.appendChild(f);", "document.body.appendChild(f); $.post('"+ v + "', {result: message.content}, function(data) {var obj = JSON.parse(data); if(obj.error1){ window.parent.document.dispatchEvent(new CustomEvent('nemidEventer', { cancel: true })); } else {  var iframe = document.getElementById('IFrameId'); iframe.src = iframe.src; var AuthenticationInfo = obj.AuthenticationInfo; parent.postMessage(AuthenticationInfo, '" + targetSite + "');}});");
            replace = replace.Replace("f.submit();", "");
            ViewBag.NemIdParameterBlock = replace;
            ViewBag.IframeUrl = frameBuilder.FrameUrl;
        }
    }
}

ESAMNew/natteravnen-esam-5b5fb689aa6c/IdeaCms/Views/DenskId/Index.cshtml
@{ 
    Layout = null;
}
<script src="~/wwwroot/scripts/js/jquery.min.js"></script>
@*<input  hidden id="pid" name="nemid" value=""/>*@
<iframe src="@Url.Action("Logon", "DenskId")"  width="100%" height="100%" border="0" style="line-height: 1.0; border: none; margin: 0; padding: 0; overflow: hidden;" scrolling="no"></iframe>

<script>
    var eventMethod = window.addEventListener ? "addEventListener" : "attachEvent";
    var eventer = window[eventMethod];
    var messageEvent = eventMethod == "attachEvent" ? "onmessage" : "message";
    var AuthenticationInfo = null;
    eventer(messageEvent, function (e) {
        AuthenticationInfo = e.data;
        $("#pid").val(AuthenticationInfo.pid);
        $("#AuthenticationInfo").val(AuthenticationInfo)
    }, false);
</script>

ESAMNew/natteravnen-esam-5b5fb689aa6c/IdeaCms/Views/DenskId/Logon.cshtml
<script src="~/wwwroot/scripts/js/jquery.min.js"></script>
@Html.Raw(@ViewBag.NemIdParameterBlock)
<div class="row">
    <div class="col s12">
        <div>
            <div style="display: table; margin: 0px auto; line-height: 1.0;">
                <iframe id="IFrameId" src="@ViewBag.IframeUrl" width="200" height="250" border="0" style="line-height: 1.0; border: none; margin: 0; padding: 0; overflow: hidden;" scrolling="no"></iframe>
            </div>
        </div>
    </div>
</div>
<script>

</script>

ESAMNew/natteravnen-esam-5b5fb689aa6c/IdeaCms/Views/DenskId/SignPdf.cshtml
@Html.Raw(@ViewBag.NemIdParameterBlock)
<div class="row">
    <div class="col s12 center-align"><br/><h3>@ViewBag.Maintitle</h3></div>
</div>
<div class="row">
    <div class="col s12">
        <div>
            <div style="display: table; margin: 0px auto; line-height: 1.0;">
                <iframe src="@ViewBag.IframeUrl" width="800" height="600" border="0" style="line-height: 1.0; border: none; margin: 0; padding: 0; overflow: hidden;" scrolling="no"></iframe>
            </div>
        </div>
    </div>
</div>

ESAMNew/natteravnen-esam-5b5fb689aa6c/IdeaCms/Views/DenskId/SignText.cshtml
@Html.Raw(@ViewBag.NemIdParameterBlock)
<div class="row">
    <div class="col s12 center-align"><br/><h3>@ViewBag.Maintitle</h3></div>
</div>
<div class="row">
    <div class="col s12">
        <div>
            <div style="display: table; margin: 0px auto; line-height: 1.0;">
                <iframe src="@ViewBag.IframeUrl" width="500" height="450" border="0" style="line-height: 1.0; border: none; margin: 0; padding: 0; overflow: hidden;" scrolling="no"></iframe>
            </div>
        </div>
    </div>
</div>