ESAMNew/natteravnen-esam-5b5fb689aa6c/IdeaCms/Controllers/ManageControllers/AdministratorsController.cs
using Core.Operations;
using IdeaCms.Filters;
using DAL.Context;
using IdeaCms.Helpers;
using System.Web.Mvc;

namespace IdeaCms.Controllers.ManageControllers
{
    [Authorisation]
    [Localization]
    public class AdministratorsController : Controller
    {
        AdministratorsOperations administratorOperations = new AdministratorsOperations();
        AdministratorGroupOperations administratorGroupOperations = new AdministratorGroupOperations();
        [Permisions]
        public ActionResult AdministratorsList()
        {
            return View(administratorOperations.GetAdministratorsList());
        }
        [Permisions]
        public ActionResult CreateAdministrator()
        {
            ViewData["AdministratorGroups"] = administratorGroupOperations.Get();
            return View();
        }
        [Permisions]
        [HttpPost]
        public JsonResult CreateAdministrator(Administrators administrator)
        {

            administrator.Password = SecurityHelper.MD5Hash(administrator.Password);
            var createAdministrator = administratorOperations.CreateAdministrator(administrator);
            if (createAdministrator)
                return Json(0);
            return Json(1);
        }
        [Permisions]
        public ActionResult UpdateAdministrator(int id)
        {
            ViewData["AdministratorGroups"] = administratorGroupOperations.Get();
            return View(administratorOperations.GetAdministratorById(id));
        }
        [Permisions]
        [HttpPost]
        public JsonResult UpdateAdministrator(Administrators administrator)
        {
            bool result = administratorOperations.UpdateAdministrator(administrator);
            if (!result)
            {
                return Json(1);
            }
            return Json(0);
        }
        [Permisions]
        public ActionResult DeleteAdministrator(int Id)
        {
            int sessionId = (int)Session["User"];
            if(sessionId.Equals(Id))
            {
                TempData["Error"] = "Unable to delete your account";
                return RedirectToAction("AdministratorsList");
            }
            administratorOperations.DeleteAdministrator(Id);
            return RedirectToAction("AdministratorsList");
        }
        [Permisions]
        public ActionResult ResetPassword(int Id)
        {
            TempData["success"] = "Password has been reset successfully. Please change password after logging. New password is: 111111";
            administratorOperations.ResetPassword(Id);
            return RedirectToAction("AdministratorsList");
        }
        public ActionResult CurrentUser(int id)
        {
            int sessionId = (int)Session["User"];
            if (!sessionId.Equals(id))
            {
                return RedirectToAction("Control", "Structure");
            }
            return View(administratorOperations.GetAdministratorById(id));
        }

        [HttpPost]
        public ActionResult CurrentUser(Administrators model)
        {
            int sessionId = (int)Session["User"];
            if (!sessionId.Equals(model.Id))
            {
                return RedirectToAction("Control", "Structure");
            }
            bool result =  administratorOperations.UpdateAdministrator(model);
            if(!result)
            {
                TempData["Error"] = "email or username is already registered";
                return RedirectToAction("CurrentUser");
            }
            return RedirectToAction("CurrentUser");
        }
        public ActionResult ChangePassword(int id)
        {
            int sessionId = (int)Session["User"];
            if (!sessionId.Equals(id))
            {
                return RedirectToAction("Control", "Structure");
            }
            ViewBag.Id = id;
            return View();
        }
        [HttpPost]
        public ActionResult ChangePassword(int id,string password,string newpassword, string confirmpassword)
        {
            int sessionId = (int)Session["User"];
            if (!sessionId.Equals(id))
            {
                return RedirectToAction("Control", "Structure");
            }
            if(string.IsNullOrEmpty(password)|| string.IsNullOrEmpty(newpassword) || string.IsNullOrEmpty(confirmpassword) )
            {
                TempData["Error"] = "Please feel all fiald.";
                return RedirectToAction("ChangePassword");
            }
            if(!newpassword.Equals(confirmpassword))
            {
                {
                    TempData["Error"] = "Password does not match the confirm password.";
                    return RedirectToAction("ChangePassword");
                }
            }
            if(!administratorOperations.CheckPassword(id,password))
            {
                {
                    TempData["Error"] = "Old password is incorrct.";
                    return RedirectToAction("ChangePassword");
                }
            }
            administratorOperations.changePassword(id, password, newpassword);
            TempData["success"] = "password was changed successfuly.";
            return RedirectToAction("CurrentUser", new { id = id });
        }
    }
}

ESAMNew/natteravnen-esam-5b5fb689aa6c/IdeaCms/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html class="flexboxtweener">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <link rel="icon" href="@Url.Content("~/Content/style/favicon.ico")"/>
    <title>@ViewBag.Maintitle</title>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"
            integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
            crossorigin="anonymous"></script>
    <!-- Styling -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    
    @Styles.Render("~/bundles/style")
    @Scripts.Render("~/bundles/materialize.js")
</head>
<body>
    @RenderBody()
    @RenderSection("scripts", required: false)
</body>
</html>

ESAMNew/natteravnen-esam-5b5fb689aa6c/IdeaCms/Views/Shared/_ManageLayoute.cshtml
@using IdeaCms.Helpers
@using Core.Operations
@using DAL.Context
@using IdeaCms.Resources
@{ 
    string User = new SessionHelper(HttpContext.Current).GetSessionUserName();
    int id = (int)Session["user"];
    List<int> permisions = new SessionHelper(HttpContext.Current).GetSessionPermisions();
    PageOperaions page = new PageOperaions();
    var pages = page.GetPageList();
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Research</title>
    <link rel="stylesheet" href="~/wwwroot/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/wwwroot/css/ManageStyle.css" />
    <link rel="stylesheet" href="~/wwwroot/css/Icons.css" />
    <script src="https://code.jquery.com/jquery-3.2.1.js"
            integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="~/wwwroot/js/Bootstrap_Confirmation.js"></script>
    <script src="~/wwwroot/js/jquery.nestable.js"></script>
    <link href="~/wwwroot/css/Nestable.css" rel="stylesheet" />
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
    <script src="~/wwwroot/js/bootstrap-select.js"></script>
    <link href="~/wwwroot/css/bootstrap-select.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-inverse sidebar" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">@ManageLayoute.DashBoard</a>
            </div>
               <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
                   <ul class="nav navbar-nav">
                       <li class="dropdown administrator_panel active">
                           <a href="#" class="dropdown-toggle" data-toggle="dropdown">@ManageLayoute.Hello @User<span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon icon-manager"></span></a>
                           <ul class="dropdown-menu forAnimate" role="menu">
                               <li><a href="@Url.Action("CurrentUser","Administrators", new { id = id })">@User</a></li>
                               <li><a href="@Url.Action("Logout", "Manage")">@ManageLayoute.log_out</a></li>
                           </ul>
                       </li>

                       @foreach (var item in pages)
                       {
                           if (permisions.Contains(item.PagesId))
                           {
                                <li><a href="@Url.Action(item.Pages.Action, item.Pages.Controller)">@item.text<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-@item.Pages.Icon"></span></a></li>
                           }
                       }
                       @foreach (var category in page.GetCategories())
                       {
                           <li class="dropdown">
                               <a href="#" class="dropdown-toggle" data-toggle="dropdown">@category<span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-@category"></span></a>
                               <ul class="dropdown-menu forAnimate" role="menu">
                                   @foreach (var item in page.GetByGroup(category))
                                   {
                                       if (permisions.Contains(item.PagesId))
                                       {
                                        <li><a href="@Url.Action(item.Pages.Action,item.Pages.Controller)">@item.text</a></li>
                                       }
                                   }
                               </ul>
                           </li>
                       }
                       <li class="dropdown">
                           <a href="#" class="dropdown-toggle" data-toggle="dropdown">@ManageLayoute.Language<span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon glyphicon-globe"></span></a>
                           <ul class="dropdown-menu forAnimate" role="menu">
                                   <li><a href="/en-US/Manage/@ViewContext.RouteData.Values["Controller"]/@ViewContext.RouteData.Values["Action"]/@ViewContext.RouteData.Values["Id"]">@ManageLayoute.English</a></li>
                                   <li><a href="/da-DK/Manage/@ViewContext.RouteData.Values["Controller"]/@ViewContext.RouteData.Values["Action"]/@ViewContext.RouteData.Values["Id"]">@ManageLayoute.Danish</a></li>
                           </ul>
                       </li>

                   </ul>
                </div>
        </div>
    </nav>
    <section class="main">
        @RenderBody()
    </section>
    <script src="~/wwwroot/js/bootstrap_select.js"></script>
    <script src="~/wwwroot/js/Manage.js"></script>
    <script src="//cdn.ckeditor.com/4.6.2/standard/ckeditor.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/ckeditor/4.5.4/adapters/jquery.js"></script>
</body>
</html>

ESAMNew/natteravnen-esam-5b5fb689aa6c/IdeaCms/Views/Shared/_NemIdLayoute.cshtml
<!DOCTYPE html>
<html class="flexboxtweener">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"
            integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
            crossorigin="anonymous"></script>
    <!-- Styling -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    @*@Styles.Render("~/bundles/style")
    @Scripts.Render("~/bundles/materialize.js")*@
</head>

<body class="homepage">
    <header>
        <!-- Dropdown Structure -->
        <ul id="nemid-dropdown" class="dropdown-content">
            <li>@Html.ActionLink("Logon", "Logon", "Nemid")</li>
        </ul>
        <nav>
            <div class="nav-wrapper">
                <a href="#" data-activates="nav-mobile" class="button-collapse right"><i class="material-icons">menu</i></a>
                <ul class="right hide-on-med-and-down">
                    <li><a class="dropdown-button" href="#!" data-activates="nemid-dropdown" data-beloworigin="true" data-hover="hover">NemID<i class="material-icons right">arrow_drop_down</i></a></li>
                </ul>
                <ul id="nav-mobile" class="side-nav">
                    <li class="no-padding">
                        <ul class="collapsible collapsible-accordion">
                            <li>
                                <a class="collapsible-header">NemID<i class="material-icons">arrow_drop_down</i></a>
                                <div class="collapsible-body">
                                    <ul>
                                        <li>@Html.ActionLink("Logon", "Logon", "Nemid")</li>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
                <script>$( document ).ready(function(){ $(".button-collapse").sideNav(); })</script>
            </div>
        </nav>
    </header>

    <main>
        <div class="container">
            @RenderBody()
        </div>
    </main>

    @RenderSection("scripts", required: false)
</body>
</html>